/**
 * scripts/extract-design-tokens.ts
 *
 * Phase 2 of the Machine-Commerce reposition (§5.1). Scans apps/web/src for
 * every design primitive in the shipped styles and writes a full inventory to
 * docs/web/DESIGN_AUDIT.md — the evidence base for the token migration map
 * (§5.4) and the hex gate (§5.4 gate).
 *
 * Run:  npx tsx apps/web/scripts/extract-design-tokens.ts
 * (from repo root, or from apps/web — the paths resolve either way.)
 *
 * Zero deps: plain fs + regex, so it runs in CI without an install step.
 */
import { readFileSync, writeFileSync, readdirSync, statSync, existsSync } from "node:fs";
import { join, relative, resolve } from "node:path";

// Resolve apps/web/src regardless of CWD.
const HERE = resolve(__dirname); // apps/web/scripts
const WEB_ROOT = resolve(HERE, ".."); // apps/web
const REPO_ROOT = resolve(WEB_ROOT, "..", ".."); // repo root
const SRC = join(WEB_ROOT, "src");
const OUT = join(REPO_ROOT, "docs", "web", "DESIGN_AUDIT.md");

const EXTS = new Set([".css", ".tsx", ".ts", ".jsx", ".js"]);
const IGNORE_DIRS = new Set(["node_modules", ".next", ".turbo", "dist", "build"]);

type Hit = { file: string; line: number; value: string };

function walk(dir: string, out: string[] = []): string[] {
  for (const name of readdirSync(dir)) {
    if (IGNORE_DIRS.has(name)) continue;
    const full = join(dir, name);
    const st = statSync(full);
    if (st.isDirectory()) walk(full, out);
    else if (EXTS.has(full.slice(full.lastIndexOf(".")))) out.push(full);
  }
  return out;
}

function scan(files: string[], re: RegExp): Map<string, Hit[]> {
  const byValue = new Map<string, Hit[]>();
  for (const file of files) {
    const rel = relative(REPO_ROOT, file);
    const lines = readFileSync(file, "utf8").split("\n");
    lines.forEach((line, i) => {
      re.lastIndex = 0;
      let m: RegExpExecArray | null;
      const local = new RegExp(re.source, re.flags.includes("g") ? re.flags : re.flags + "g");
      while ((m = local.exec(line)) !== null) {
        const value = (m[1] ?? m[0]).trim();
        if (!value) continue;
        const arr = byValue.get(value) ?? [];
        arr.push({ file: rel, line: i + 1, value });
        byValue.set(value, arr);
      }
    });
  }
  return byValue;
}

function sortByCount(m: Map<string, Hit[]>): [string, Hit[]][] {
  return [...m.entries()].sort((a, b) => b[1].length - a[1].length || a[0].localeCompare(b[0]));
}

function table(rows: [string, Hit[]][], valueHeader: string, allowlistPredicate?: (v: string) => boolean): string {
  const out: string[] = [`| ${valueHeader} | Uses | Files (top 4) |`, `| --- | ---: | --- |`];
  for (const [value, hits] of rows) {
    const files = [...new Set(hits.map((h) => h.file))];
    const shown = files.slice(0, 4).map((f) => `\`${f}\``).join(", ") + (files.length > 4 ? ` +${files.length - 4}` : "");
    const flag = allowlistPredicate && !allowlistPredicate(value) ? " ⚠️" : "";
    out.push(`| \`${value}\`${flag} | ${hits.length} | ${shown} |`);
  }
  return out.join("\n");
}

function main() {
  if (!existsSync(SRC)) {
    console.error(`[extract] src not found at ${SRC}`);
    process.exit(1);
  }
  const files = walk(SRC);

  const customProps = scan(files, /(--[a-zA-Z0-9-]+)\s*:/); // definitions and uses both; we count all
  const hex = scan(files, /#[0-9a-fA-F]{3,8}\b/);
  const rgb = scan(files, /(rgba?\([^)]*\))/);
  const hsl = scan(files, /(hsla?\([^)]*\))/);
  const oklch = scan(files, /(oklch\([^)]*\))/);
  const fontFamily = scan(files, /font-family\s*:\s*([^;]+);/);
  const radius = scan(files, /border-radius\s*:\s*([^;]+);/);
  const shadow = scan(files, /box-shadow\s*:\s*([^;]+);/);

  // Hex allowlist per §5.4 gate.
  const HEX_ALLOWLIST_FILES = ["TerminalWindow", "chart", "palette", "og", "opengraph", "icon"];
  const hexFilesOffAllowlist = new Map<string, Hit[]>();
  for (const [value, hits] of hex.entries()) {
    const offending = hits.filter((h) => !HEX_ALLOWLIST_FILES.some((a) => h.file.toLowerCase().includes(a.toLowerCase())));
    if (offending.length) hexFilesOffAllowlist.set(value, offending);
  }

  const now = new Date().toISOString().slice(0, 10);
  const md: string[] = [];
  md.push(`# Design Audit — extracted tokens & hardcoded values`);
  md.push(``);
  md.push(`> Auto-generated by \`apps/web/scripts/extract-design-tokens.ts\` on ${now}. Do not hand-edit; re-run the script. The migration map (§5.4) is maintained by hand below the divider at the bottom.`);
  md.push(``);
  md.push(`Scanned **${files.length}** files under \`apps/web/src\` (\`.css .tsx .ts .jsx .js\`).`);
  md.push(``);
  md.push(`| Category | Distinct values | Total occurrences |`);
  md.push(`| --- | ---: | ---: |`);
  const cat = (m: Map<string, Hit[]>) => [m.size, [...m.values()].reduce((n, a) => n + a.length, 0)];
  md.push(`| CSS custom properties | ${cat(customProps).join(" | ")} |`);
  md.push(`| Hardcoded hex | ${cat(hex).join(" | ")} |`);
  md.push(`| rgb()/rgba() | ${cat(rgb).join(" | ")} |`);
  md.push(`| hsl()/hsla() | ${cat(hsl).join(" | ")} |`);
  md.push(`| oklch() | ${cat(oklch).join(" | ")} |`);
  md.push(`| font-family | ${cat(fontFamily).join(" | ")} |`);
  md.push(`| border-radius | ${cat(radius).join(" | ")} |`);
  md.push(`| box-shadow | ${cat(shadow).join(" | ")} |`);
  md.push(``);

  md.push(`## CSS custom properties (by usage)`);
  md.push(table(sortByCount(customProps), "Property"));
  md.push(``);
  md.push(`## Hardcoded hex colors (⚠️ = off the §5.4 allowlist, must be migrated)`);
  md.push(table(sortByCount(hex), "Hex", (v) => hexFilesOffAllowlist.get(v) === undefined));
  md.push(``);
  md.push(`### Hex gate status`);
  if (hexFilesOffAllowlist.size === 0) {
    md.push(`✅ **PASS** — no hardcoded hex outside the allowlist (\`${HEX_ALLOWLIST_FILES.join(", ")}\`).`);
  } else {
    md.push(`❌ **FAIL** — ${hexFilesOffAllowlist.size} hex value(s) appear in non-allowlisted files:`);
    md.push(``);
    for (const [value, hits] of sortByCount(hexFilesOffAllowlist)) {
      const files = [...new Set(hits.map((h) => h.file))];
      md.push(`- \`${value}\` → ${files.slice(0, 6).map((f) => `\`${f}\``).join(", ")}${files.length > 6 ? ` +${files.length - 6}` : ""}`);
    }
  }
  md.push(``);
  md.push(`## rgb()/rgba() (by usage)`);
  md.push(table(sortByCount(rgb), "Value"));
  md.push(``);
  md.push(`## oklch() (by usage)`);
  md.push(oklch.size ? table(sortByCount(oklch), "Value") : "_none_");
  md.push(``);
  md.push(`## hsl()/hsla() (by usage)`);
  md.push(hsl.size ? table(sortByCount(hsl), "Value") : "_none_");
  md.push(``);
  md.push(`## font-family declarations`);
  md.push(table(sortByCount(fontFamily), "Value"));
  md.push(``);
  md.push(`## border-radius declarations`);
  md.push(table(sortByCount(radius), "Value"));
  md.push(``);
  md.push(`## box-shadow declarations`);
  md.push(shadow.size ? table(sortByCount(shadow), "Value") : "_none_");
  md.push(``);
  md.push(`<!-- MIGRATION-MAP-BELOW: hand-maintained, not overwritten by the script -->`);
  md.push(``);

  // Preserve a hand-maintained migration map if it already exists.
  let existing = "";
  if (existsSync(OUT)) {
    const prev = readFileSync(OUT, "utf8");
    const idx = prev.indexOf("<!-- MIGRATION-MAP-BELOW");
    if (idx !== -1) {
      const after = prev.slice(idx);
      const nl = after.indexOf("\n");
      existing = after.slice(nl + 1).trim();
    }
  }
  if (existing) md.push(existing);

  writeFileSync(OUT, md.join("\n") + "\n");
  console.log(`[extract] wrote ${relative(REPO_ROOT, OUT)}`);
  console.log(`[extract] hex gate: ${hexFilesOffAllowlist.size === 0 ? "PASS" : `FAIL (${hexFilesOffAllowlist.size} off-allowlist)`}`);
  if (hexFilesOffAllowlist.size > 0) process.exitCode = 0; // report-only during migration; the truth-lint test enforces the gate
}

main();
